### ISSUE TITLE
Dichiarazione Pubblico dominio?

### ISSUE THREAD

**Issue by ruphy** [italia-it/spid-idp-login-layout#5]
Nella licenza attuale viene dichiarato che:

> Essendo un lavoro di AgID, Agenzia per l'Italia Digitale della Presidenza del Consiglio dei Ministri, questo progetto è di pubblico dominio.

ma questo non è corretto: AgID deve solo rilasciare software sotto licenza aperta.
Nel caso si voglia comunque adottare la licenza CC-0, le PR #2 e #3 sistemano il problema.
Se si preferisce passare alla licenza BSD, suggerita dal'analisi del Team Digitale, le PR #2 e #4 sistemano il problema

**Comment by umbros** [comment]
Scelta licenza apache 2.0 e altre licenze spostate su altro file
